spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${dbhost:}:5444/hospitalpoc
    username: sumana
    password: abcd1234
    
   
    hikari:
      minimum-idle: 9
      maximum-pool-size: 9
      idle-timeout: 30000
      pool-name: cqrspoc-pool
      max-lifetime: 200000
      connection-timeout: 30000
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true

  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
      naming:
        #strategy: org.hibernate.cfg.ImprovedNamingStrategy
      connection:
        provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.cache.hazelcast.instance_name: HospitalPocHzCache
      hibernate.cache.use_minimal_puts: true
      hibernate.cache.hazelcast.use_lite_member: true
      
